### ISSUE TITLE
minikube or docker-for-desktop kubernetes support 

### ISSUE THREAD

**Issue by gadelkareem** [storageos/deploy#10]
On both minikube or docker-for-desktop, storageos pod fails to start with `Error: failed to start container "enable-lio": Error response from daemon: linux mounts: path /sys is mounted on /sys but it is not a shared mount`
And I am not sure how to install `linux-image-extra-$(uname -r)` on OSX

**Comment by Arau** [comment]
The error you mention indicates that your docker installation doesn't have mount propagation installed.
https://docs.storageos.com/docs/prerequisites/mountpropagation

On the other hand, StorageOS prerequisites page indicates the supported platforms. 
https://docs.storageos.com/docs/prerequisites/systemconfiguration

StorageOS requires the following kernel modules, hence you can't install StorageOS without them. 
- target_core_mod
- tcm_loop
- target_core_file
- configfs

I believe that the minikube kernel doesn't come with these modules by default. I would recommend to use a Vagrant installation of Kubernetes to install StorageOS and play with it. 

There is also resources to get familiar with StorageOS in play.storageos.com that won't require you to run StorageOS in your machine.

**Comment by gadelkareem** [comment]
I see, it would be nice to get it working with minikube in the future though. Feel free to close it or keep it as feature request.

**Comment by Arau** [comment]
Thank you @gadelkareem. I appreciate your feedback and take it into consideration so we will look into integrating with minikube.
